# Generated by Django 3.2.5 on 2021-10-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500, null=True)),
                ('Uploadfiles', models.FileField(upload_to='paperwebapp/files')),
                ('UpTime', models.DateTimeField()),
            ],
        ),
    ]
