# Generated by Django 3.2.5 on 2021-10-21 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperwebapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='UpTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='files',
            name='Uploadfiles',
            field=models.FileField(null=True, upload_to='paperwebapp/files'),
        ),
    ]
